apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
      - image: gcr.io/absolute-nexus-455918-j8/backend:v6
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: FACE_VERIFICATION_URL
          value: "https://face-verification-v5heid6ezq-uc.a.run.app"
