steps:
  # Build and push the face verification service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/evote-repo/face-verification:v1', '-f', 'Dockerfile', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/evote-repo/face-verification:v1']
  
  # Build and push the backend service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/evote-repo/backend:v1', '-f', 'Dockerfile.backend', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/evote-repo/backend:v1']

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/evote-repo/face-verification:v1'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/evote-repo/backend:v1'

timeout: '3600s'  # Increase timeout to 1 hour for building the face verification image 