steps:
  # Build and push the face verification service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/absolute-nexus-455918-j8/face-verification:v3', '-f', 'Dockerfile', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/absolute-nexus-455918-j8/face-verification:v3']
  
  # Build and push the backend service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/absolute-nexus-455918-j8/backend:v7', '-f', 'Dockerfile.backend', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/absolute-nexus-455918-j8/backend:v7']
  
  # Deploy the backend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image=gcr.io/absolute-nexus-455918-j8/backend:v7'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=FACE_VERIFICATION_URL=https://face-verification-369369713332.us-central1.run.app,NODE_ENV=production'
      - '--set-secrets=JWT_SECRET=jwt-secret:latest,MONGODB_URI=mongodb-uri:latest,GEMINI_API_KEY=gemini-api-key:latest'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'

images:
  - 'gcr.io/absolute-nexus-455918-j8/face-verification:v3'
  - 'gcr.io/absolute-nexus-455918-j8/backend:v7'

timeout: '3600s'  # Increase timeout to 1 hour for building the face verification image